#!/usr/bin/env python3


import os
from diffusers import StableDiffusionImg2ImgPipeline


model_id = "runwayml/stable-diffusion-v1-5"
MODEL_CACHE = "diffusers-cache"

os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    model_id,
    cache_dir=MODEL_CACHE,
)